# Generated by Django 4.0.5 on 2022-06-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.TextField(null=True, verbose_name='biography'),
        ),
        migrations.AddField(
            model_name='account',
            name='fname',
            field=models.CharField(max_length=30, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='account',
            name='lname',
            field=models.CharField(max_length=30, null=True, verbose_name='last name'),
        ),
    ]
