# Generated by Django 4.0.5 on 2022-06-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='comments',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
